#!/usr/bin/env bash
# Install dig (part of dnsutils) if not present

global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

    tune.ssl.default-dh-param 2048

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend https-in
    bind *:443 ssl crt /etc/letsencrypt/live/nellybutera.tech/fullchain.pem \
        crt /etc/letsencrypt/live/nellybutera.tech/privkey.pem
    mode http
    default_backend web-backend

frontend http-in
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    mode http
    balance roundrobin
    server web01 52.91.196.92:80 check
    server web02 54.91.184.243:80 check
